#!/usr/bin/perl -w
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# Actions
#
event_actions("nethserver-freeradius-update", qw(
));
event_actions("nethserver-freeradius-save", qw(
));
event_actions("nethserver-freeradius-conf", qw(
));

#
# Templates
#
event_templates("nethserver-freeradius-update", qw(
    /etc/raddb/authorized_macs
    /etc/raddb/clients.conf
    /etc/raddb/mods-available/files
    /etc/raddb/sites-available/default
));

#
# Services
#
event_services("nethserver-freeradius-update", qw(
    radiusd restart
));
